version: '3.8'

services:
  postgres:
    image: postgres:15 
    container_name: postgres_container
    environment:
      POSTGRES_DB: prontuario_db  
      POSTGRES_USER: prontuario_user 
      POSTGRES_PASSWORD: secure_password  
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data  

volumes:
  postgres_data:  
